collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://sandstormnick.github.io/"
baseurl: "/Jekyll-Theme-Verdant"

exclude:
  - docker-compose.yml

sass:
  quiet_deps: true
  load_paths:
    - /home/runner/work/Jekyll-Theme-Verdant/Jekyll-Theme-Verdant/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.3.5/assets/stylesheets