version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    container_name: jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "bundle install &&
               bundle add rexml &&
               jekyll serve --host 0.0.0.0 --watch --force_polling"